{"uuid": "33102b83-0954-4f73-a334-fce52d7caada", "children": ["258a50b3-be13-4d2a-8e0c-dc773f99d1f4", "dc0bbcd7-9e53-4f4f-ab6b-a4d2a05511eb", "2a4e0974-8abc-4300-8cd2-151baa9029a2", "4dcf2d62-9209-4d14-9b47-efc598661b17", "009aff5c-9a74-41b7-8e06-81fb5cb18397", "0eef2a81-563f-43c1-8fb8-43ffc2e82ee3", "92c64932-6357-4f32-942b-25f2a52fcc7d", "a82e5f07-b1e9-458c-8d02-0511de439867", "bb0666d1-7527-4271-9953-48876a358bfa", "41bda961-3dbe-4221-993c-3d8b5586967a", "1171ae82-53d7-41e8-93ef-c0ff9659e575", "3e8753d6-ea95-451e-92dc-61b1e4b4c9c0", "0c5673aa-7cf7-4a7a-a77e-8576b9495ef7", "4c8d5bb0-3416-4051-a972-9e08b7a5a601"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002001383E960>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"D:\\PyProjects\\exam\\qaa_project_gcore\\pythonProject1\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\PyProjects\\exam\\qaa_project_gcore\\pythonProject1\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\PyProjects\\exam\\qaa_project_gcore\\pythonProject1\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\PyProjects\\exam\\qaa_project_gcore\\pythonProject1\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1149, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\PyProjects\\exam\\qaa_project_gcore\\pythonProject1\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 916, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\PyProjects\\exam\\qaa_project_gcore\\pythonProject1\\tests\\conftest.py\", line 13, in browser\n    driver = webdriver.Remote(command_executor=\"http://localhost:4444/wd/hub\",\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\PyProjects\\exam\\qaa_project_gcore\\pythonProject1\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 208, in __init__\n    self.start_session(capabilities)\n  File \"D:\\PyProjects\\exam\\qaa_project_gcore\\pythonProject1\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 292, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\PyProjects\\exam\\qaa_project_gcore\\pythonProject1\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 345, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\PyProjects\\exam\\qaa_project_gcore\\pythonProject1\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 302, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\PyProjects\\exam\\qaa_project_gcore\\pythonProject1\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 322, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\PyProjects\\exam\\qaa_project_gcore\\pythonProject1\\.venv\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 144, in request\n    return self.request_encode_body(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\PyProjects\\exam\\qaa_project_gcore\\pythonProject1\\.venv\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 279, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\PyProjects\\exam\\qaa_project_gcore\\pythonProject1\\.venv\\Lib\\site-packages\\urllib3\\poolmanager.py\", line 444, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\PyProjects\\exam\\qaa_project_gcore\\pythonProject1\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 877, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"D:\\PyProjects\\exam\\qaa_project_gcore\\pythonProject1\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 877, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"D:\\PyProjects\\exam\\qaa_project_gcore\\pythonProject1\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 877, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"D:\\PyProjects\\exam\\qaa_project_gcore\\pythonProject1\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 847, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"D:\\PyProjects\\exam\\qaa_project_gcore\\pythonProject1\\.venv\\Lib\\site-packages\\urllib3\\util\\retry.py\", line 515, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1706852515696, "stop": 1706852532010}], "start": 1706852515696, "stop": 1706852533455}